# Basic
title: Vno Jekyll
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/Hyu0529/Hyu0529.github.io" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://wouldyoubreakit.com/">@Hyu</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Hyu
    # duoshuo: 
    
# Social
social:
    weibo: Hyu
    github: Hyu0529
    twitter:
    gplus: 
    mail: 1576960522@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
